### ISSUE TITLE
Navigation bar - dark mode

### ISSUE THREAD

**Issue by b4c1c** [b4c1c/city_tour_project#1]
Navigation bar doesn't correctly switch to dark mode. 
I don't where to problem lies.

**Comment by 1mazin** [comment]
I would like to help you with this issue

**Comment by JA-26-01** [comment]
Can you share the code snippet? Then we can see where is the error, if any.

Also, if you are using bootstrap, this should work

    <nav class="navbar navbar-dark bg-dark">
    
    </nav>

**Comment by Rishav1707** [comment]
shall I work on this issue? @b4c1c

**Comment by b4c1c** [comment]
> shall I work on this issue? @b4c1c

You are free to work on it! Thank you

This is my first issue I ever posted on GitHub and I'm also learning how to handle entire process :)

**Comment by Rishav1707** [comment]
OK

**Comment by b4c1c** [comment]
> OK

It is just resolved a minute ago and it is working. 
I will close issue now.
Thank you for your input!

**Comment by Rishav1707** [comment]
OK
